### ISSUE TITLE
Arbitrary file type support

### ISSUE THREAD

**Issue by tfiers** [eltos/PasteIntoFile#12]
Use case: I want to extract diagrams made in PowerPoint.
They are available in vector format on the clipboard, as seen by NirSoft's InsideClipboard:

![image](https://user-images.githubusercontent.com/3773558/201518546-f8f6ce8e-b6f7-4ccc-a704-223bbbc3c7fc.png)

I can also paste them in e.g. Inkscape as vector graphics.

But PasteIntoFile does not seem to support pasting vector graphics.
(There is `pdf`, but that seems to contain just the flattened image).

Would it be possible to add svg as a supported file format?

<br>

---
More generally, I wondered if it would be possible to let the user choose any arbitrary file format -- and then choose the entry in the clipboard to go into it, i.e. choose the 'mapping'.

This is presumably a larger code change than just adding `.svg` support; and it is something I do not need at the moment.

**Comment by eltos** [comment]
Regarding SVG support I implemented something in 24dcb07bc0f34d96d48255bfbbd1d985ec8ca7ac. It's not yet released but you can try the debug build from the _next_ branch and see if that works for you:
https://github.com/eltos/PasteIntoFile/suites/8792849471/artifacts/399543817

**Comment by tfiers** [comment]
Yup, works for me!

**Comment by eltos** [comment]
Great.   
I'll leave this one open to think about your Idea on arbitrary mapping.

**Comment by eltos** [comment]
> More generally, I wondered if it would be possible to let the user choose any arbitrary file format -- and then choose the entry in the clipboard to go into it, i.e. choose the 'mapping'.

I won't implement this anytime soon, mainly because I think - given the magnitude of data typically present in the clipboard - it will be more disturbing than helpful. This is because data is usually duplicated in many formats, and there are a lot of custom binary formats which usually don't have a file type association and are rarely to be saved. I would like to keep things simple for the user, so they get what they want easily and quickly (and often without any GUI interaction), and not overwhelm them with a long list of cryptic formats to choose from.

Also, if someone requires saving arbitrary clipboard data as binary, [NirSoft's InsideClipboard](https://www.nirsoft.net/utils/inside_clipboard.html) can already do this. 

Having said this, I'll close this issue.
