### ISSUE TITLE
Add acknowledgment to original PasteAsFile

### ISSUE THREAD

**Issue by tfiers** [eltos/PasteIntoFile#15]
This software seems to be a descendant of https://pasteasfile.org ([source](https://twitter.com/CatoMinor3/status/1598312162929377283)).
But there is no acknowledgment of that in the docs/readme.
(That is not this repo's fault. It's the original open source clone, https://github.com/EslaMx7/PasteIntoFile, that seems to have forgotten to mention that. See also the footnote in that repo [here](https://github.com/EslaMx7/PasteIntoFile/issues/49#user-content-fn-1-db87f3f4a0e1b2244d16ce5f0ff37ec1)).

**Comment by eltos** [comment]
How to verify this? A random Twitter user saying "I *think* this is a 1:1 copy" is not very convincing. The software you are linking is indeed similar in functionality and GUI - but there are more programs out there which follow the same idea (e.g. [Paste to File](https://apps.microsoft.com/store/detail/paste-to-file/9PM34S06CFVJ)). Since it is closed source, I doubt that EslaMx7 copied anything from that project. Also, if I look how that tool is done and what features it has, there is not much in common with the first version of EslaMx7 other than the idea to paste clipboard data. He might have been inspired, or might not even have known about it (after all, the idea is very obvious). Only he can tell that. I think one must verify this fact before claiming some ancestry.

**Comment by eltos** [comment]
Don't get me wrong, I'll happily add references. I just want to make sure we get the facts right. A fact-proof statement could for example be
> This program is simmilar to [Paste As File](https://pasteasfile.org) and [Paste To File](https://apps.microsoft.com/store/detail/paste-to-file/9PM34S06CFVJ).
